### ISSUE TITLE
Suggestion: Update README

### ISSUE THREAD

**Issue by whoiskevinrich** [LAX1DUDE/eaglercraft#1]
A great README is a good way to put your best foot forward with a project. I like to use this [template](https://github.com/jehna/readme-best-practices) as a base because it guide's the user's eyes to what they are looking for.

Snazzy project! Which files have you written yourself? Consider highlighting these with links in the Updated README file. :)

**Comment by LAX1DUDE** [comment]
yeah I need to look into that, I didn't have contributions in mind when I made this it's more of a reference for other people attempting to port fixed-function opengl games to webgl and teavm.

the packages labeled eaglercraft in the src tree and the eaglercraft package in the bungeecord source are all original code, the other half of the original code is just thousands of modifications to the minecraft source, about 25% of lines are altered. I had a repository keeping track of my changes to the contents of what is now src/main/java previously but I didn't preserve the commits when consolidating it with all the other code to github because the different parts of the project were all over the place because I didn't have sharing in mind when I first started working on this and I was just too lazy to merge the commits from the parts that did have a local git repository with the commits of parts that did. probably a poor decision looking back now but I was lazy when I first started working on this it was a personal thing. I might fix that actually I see the benefit in understanding the history of at least seeing what exactly what was changed in every file of the minecraft source, and I will update the readme to help identify the reusable code for other applications

**Comment by whoiskevinrich** [comment]
All very understandable. 

For git, Scott Hanselman has some great, understandable, and fun (as much as possible) videos about git on [YouTube](https://www.youtube.com/watch?v=WBg9mlpzEYU) with some practical examples.

**Comment by LAX1DUDE** [comment]
surprise surprise I deleted the old local repo with the commit history to the minecraft source after copying it to this repo's workspace because I thought I didn't need it anymore, so unfortunately I can't provide a definite history of changes now

**Comment by LAX1DUDE** [comment]
Hey guys sorry I was gonna respond to this like four days ago but I forgot I haven't been checking my email lately for some reason, I guess I just haven't been expecting anything.

I'm really sorry about the demo link going down it must be frustrating to be messing around with WAMP now to play the game instead of just being able to load it off of my server already working right. My domain expired because I didn't catch the warning email and then because of that I lost my cloudflare configuration and if I get a new domain I also have to rewrite all the nginx configuration files I have and and it just feels like so much work so I haven't been in the mood

@Heath123 The reason this never got attention and never will until faster hardware comes out is because this is an old version of minecraft that has (multiplayer) lighting updates often processed on the client instead of the server for minor changes like placing or breaking a torch, and this flood-fill algorithm of mojang's uses a very large number of recursive function calls to complete the task which the JVM seems to optimize pretty well. But when the same code with all the recursive function calls is compiled by teavm, the form of javascript produced cannot be optimized at all as well in V8 as the java binary version can be in the JVM. So the main loop is just plagued with random pauses sometimes lasting multiple seconds when these client side lighting updates are triggered

If you're wondering, I used an older and crappier version of minecraft because I preferred to port the old networking engine that just uses `java.io.DataInputStream` and `java.io.DataOutputStream` for sending and recieving packets to websocket because I didn't want to find a way to emulate the newer io.netty network engine in teavm instead (even though I probably should have and it probably would've been simple to figure out if I hadn't immediately decided in the first 15 seconds that I couldn't be bothered)

The reason I created this in the first place not considering the age of this version of the game is so I could play actual multiplayer minecraft with the kids I had classes with at school on our school chromebooks. I even created one of those hacked `javascript:` bookmarks that loads `classes.js` and `assets.epk` via XHR and launches the game with javascript's `window.open` in one of those empty `about:blank` windows because those windows don't go into the chromebook's history. When I finally reached the point though after more than a month of work where the graphics were all working on my desktop I did my first test of all this on my school chromebook and when it loaded the chromebook was already struggling at a single digit frame rate just on the character skin selection screen, simply rendering the character preview was visually already too slow to be deemed 'playable'.

And my desktop is pretty beefy so the already long pauses I experienced when I was still testing this in my desktop browser will be way longer on most regular systems.

Therefore this is all just basically a gimmick proof-of-concept teavm demo for now until hardware gets faster or someone fixes the client side lighting updates and forces all lighting updates to the (JVM) server which I could probably do myself in a week or two after how intimately I've studied the minecraft source code over the years but I'm very focused right now on some other projects I'm doing currently involving digital electrical engineering and lasers and a game in C++ and OpenGL and knowing this project will still never work on a chromebook even if I drop everything and do all that extra work just makes it feel pointless

**Comment by Heath123** [comment]
It works fine on my Chromebook, at about 30ish FPS

**Comment by LAX1DUDE** [comment]
@Heath123 no way really? that's cool. How old are you (I'm assuming you have a chromebook because you're still in high school or younger but correct me if I'm wrong) I'm now 17 but I quit school so I don't have a chromebook anymore to experiment with.

I did try to run it on my chromebook a second time last year and there was an uncaught webgl driver crash when I tried to join the server that made the canvas go black but it looks like they've fixed it if it's working for you now.

The windows d3d11 drivers were also not originally compatible with this because enabling the `GL_TEXTURE_MAX_ANISOTROPY_EXT` texture parameter is not supported when the `GL_NEAREST_MIPMAP_LINEAR` mipmap mode enabled for downscaling the terrain texture combined with `GL_NEAREST` enabled for upscaling the terrain texture. That specific combination breaks it which just happens to be in my opinion the best filtering profile for the texture on minecraft chunks. I opened a bug report on the google ANGLE bug tracker for this issue over a year ago and someone deleted it so it was probably fixed.

Did you have to make any changes to the source to get it to work on your chromebook? I'd definitely like to see them I live in my own world when I make stuff like this I don't get any feedback

**Comment by LAX1DUDE** [comment]
and I'll probably fix my website and actually host a working demo server so the demo page on my website can feature actual gameplay. I should've done this all along but when I set up the demo page for some reason my thought process was that didn't want to expose my IP address for a demo, I just kind of forgot the fact that I specifically set this code up so I can use cloudflare to proxy the websocket's connection to the server so it would not expose my real IP address to any firewall because the school district IT people know my IP address from 8th grade when I was connecting people's chromebooks to a VPN I was hosting that manipulates DNS packets to disable all the site block extensions. So basically I could've used cloudflare all along and provided a working demo on my website I just wasn't paying attention at the end when I was all burnt out after working on this nonstop for 2 months and now being under the impression that all my work had been for nothing so in the 5 minutes I spent pasting it into my nginx and setting up the server list config I just didn't even remember the cloudflare detail

**Comment by LAX1DUDE** [comment]
I need to make some changes to the assets first I need to get rid of the GTA music I don't know why I thought it was so funny at the time and I need to remove the offensive default username generator so it's not literally the first thing that loads when someone visits the link

**Comment by Heath123** [comment]
> @Heath123 no way really? that's cool. How old are you (I'm assuming you have a chromebook because you're still in high school or younger but correct me if I'm wrong) I'm now 17 but I quit school so I don't have a chromebook anymore to experiment with.
> 
> I did try to run it on my chromebook a second time last year and there was an uncaught webgl driver crash when I tried to join the server that made the canvas go black but it looks like they've fixed it if it's working for you now.
> 
> The windows d3d11 drivers were also not originally compatible with this because enabling the `GL_TEXTURE_MAX_ANISOTROPY_EXT` texture parameter is not supported when the `GL_NEAREST_MIPMAP_LINEAR` mipmap mode enabled for downscaling the terrain texture combined with `GL_NEAREST` enabled for upscaling the terrain texture. That specific combination breaks it which just happens to be in my opinion the best filtering profile for the texture on minecraft chunks. I opened a bug report on the google ANGLE bug tracker for this issue over a year ago and someone deleted it so it was probably fixed.
> 
> Did you have to make any changes to the source to get it to work on your chromebook? I'd definitely like to see them I live in my own world when I make stuff like this I don't get any feedback

I'm 17 as well, it's a personal Chromebook though (I did try running vanilla Minecraft in a Linux container but it just crashed and used too much storage). I didn't change the source, I just compiled it and it works as is, I'm on an Acer Chromebook 11 if that helps.

**Comment by Heath123** [comment]
Screen recording at https://youtu.be/Y9Xq4zkKSuE (it's usually not this laggy and the mouse pointer is only visible in the recording)

**Comment by Heath123** [comment]
I quite like the background music

**Comment by schoolgaminghd** [comment]
please send bookmarklet.

**Comment by LAX1DUDE** [comment]
> please send bookmarklet.

bookmarklets were removed from chrome last year

**Comment by LAX1DUDE** [comment]
Okay I added a very large and detailed section with 7 paragraphs on how to set up and manage a server, and I made precompiled binaries available in the stable-download directory of the repository to make the installation process take like 10 minutes instead of hours. And I added this link [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) to the readme featuring a working demo and a working public creative mode and survival mode server
