### ISSUE TITLE
Adding custom servers does not work

### ISSUE THREAD

**Issue by oliver408i** [LAX1DUDE/eaglercraft#118]
I was able to decrypt the string, but it also gives me a bunch of '?' and when I tried to only edit the ip/port part, reencypt it, it doesn't work. The screen is blank and has no servers. The readme asked to put the string into NBT editor, but I thought you needed it to be a file. I didn't see any way to download it as a file.

**Comment by LAX1DUDE** [comment]
You don't know how to use the encode/decode site. Download `stable-download/server_template.dat` and open it in an NBT editor. Make your changes and save and **upload the file to the site instead of opening the binary in a text editor and copy pasting the corrupted text**. Press encode and then download the resulting file and open the resulting file in a text editor and copy the base64 in the file and paste it into the string in `index.html`.
