### ISSUE TITLE
[Enhancement] ToggleSprint

### ISSUE THREAD

**Issue by MegaTKC** [LAX1DUDE/eaglercraft#12]
Hello!
I am playing Minecraft with my friends using Eaglercraft. Its been really fun. We are playing a parkour course and we cant make this jump because of sometimes we press on W two times and we don't sprint. It would be really nice if we could get toggle/autosprint.

**Comment by LAX1DUDE** [comment]
there's a sprint key in the controls menu in the options screen, it defaults to R instead of CTRL because CTRL+W closes the tab on chrome

![https://cdn.discordapp.com/attachments/378764518081429506/932818917179658260/unknown.png](https://cdn.discordapp.com/attachments/378764518081429506/932818917179658260/unknown.png)
