### ISSUE TITLE
Offline version tells me I am hacking

### ISSUE THREAD

**Issue by cooldude-222** [LAX1DUDE/eaglercraft#20]
I am using the offline version and the integrity test keeps failing.

**Comment by LAX1DUDE** [comment]
The survival server no longer accepts connections from any of the releases of the game posted on this repository, only the official demo copy of the game at [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) can join the survival server now.

I published a commit removing the survival demo from all default server lists on this repository, you can download the now obsolete new version of the offline file version without the survival server available here: [https://github.com/LAX1DUDE/eaglercraft/commit/3d73f98d49a36df65bcb1b9149f203f6c7e85329](https://github.com/LAX1DUDE/eaglercraft/commit/3d73f98d49a36df65bcb1b9149f203f6c7e85329)

It has to be this way now because people are developing hacked clients using the code on this repository and they are specifically designing them to hack on the survival demo
