### ISSUE TITLE
How to make a private server

### ISSUE THREAD

**Issue by JontayOfficial** [LAX1DUDE/eaglercraft#22]
I've been wondering how to make a private server so I can play with my friends. I really want to know. Thanks, Jontay.

**Comment by LAX1DUDE** [comment]
it is literally the third paragraph of the README please try harder [https://github.com/LAX1DUDE/eaglercraft#installing](https://github.com/LAX1DUDE/eaglercraft#installing)

**Comment by JontayOfficial** [comment]
I'm dumb af this is some really technical stuff I need help

**Comment by JontayOfficial** [comment]
it keeps on saying cant connect

**Comment by LAX1DUDE** [comment]
if you're using the demo site at [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) it does not support the configuration in the `stable-download` folder because the site is hosted on an HTTPS URL and the websocket hosted by Eaglercraft bungeecord is treated as an HTTP URL by the browsers and pages on HTTPS are no longer allowed to load any other URLs unless they are also on HTTPS URLs so you need to host `stable-download/web` on your own HTTP server or use `stable-download/Offline_Download_Version.html` to connect correctly

**Comment by JontayOfficial** [comment]
im on a chromebook

**Comment by JontayOfficial** [comment]
im now in the local version, what do i do next

**Comment by pubbyman99** [comment]
i want to add mods to it on the html website can you help me
