### ISSUE TITLE
cannot connect to private server

### ISSUE THREAD

**Issue by Yamipengui** [LAX1DUDE/eaglercraft#23]

**Comment by JontayOfficial** [comment]
same

**Comment by LAX1DUDE** [comment]
if you're using the demo site at [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/) it does not support the configuration in the `stable-download` folder because the site is hosted on an HTTPS URL and the websocket hosted by Eaglercraft bungeecord is treated as an HTTP URL by the browsers and pages on HTTPS are no longer allowed to load any other URLs unless they are also on HTTPS URLs so you need to host `stable-download/web` on your own HTTP server or use `stable-download/Offline_Download_Version.html` to connect correctly. If you want people to help you on github you need to provide more information then a 5 word generic misspelled ambiguous title that could mean anything to someone who's not already babysitting you through the whole process
