### ISSUE TITLE
Minecraft 1.5.2 download

### ISSUE THREAD

**Issue by REA-PER** [LAX1DUDE/eaglercraft#34]
Can you please enable singleplayer on the Minecraft download? so I can make worlds.

**Comment by ayunami2000** [comment]
Singleplayer has been fully removed. It's not possible to just "enable" it. The button is all that remains of singleplayer and it could take quite a long time to reimplement it. (Not to mention the game would be super slowed down once it IS implemented)

**Comment by LAX1DUDE** [comment]
Someone already posted this question it's literally in the list of open issues which I know you saw because it's shown before you open an issue. It's extremely annoying and counter-productive to open new issues just because you're too lazy to read if the issue literally named '[Enhancement] Singleplayer Mode' doesn't already answer your question for some reason, and spoiler alert it does so please check this links:

Issue [https://github.com/LAX1DUDE/eaglercraft/issues/7](https://github.com/LAX1DUDE/eaglercraft/issues/7)
