### ISSUE TITLE
Can't move when the game is in an iframe

### ISSUE THREAD

**Issue by Abnumality** [LAX1DUDE/eaglercraft#37]
I have code on my website to iframe the game, and you can only click and move your camera whenever it's in an iframe, not move.

**Comment by LAX1DUDE** [comment]
This is most likely a thing the browser does to prevent people from creating cross-site-scripting keyloggers, I think you are limited to only text fields on form objects for keyboard event listeners in an iframe. Try replacing the existing document's innerHTML with the game instead of creating a new window and writing the html to that window

[https://stackoverflow.com/questions/3633906/onkeydown-event-not-working-when-focused-on-iframe](https://stackoverflow.com/questions/3633906/onkeydown-event-not-working-when-focused-on-iframe)

**Comment by Abnumality** [comment]
Mistakenly closed this trying to edit

**Comment by LAX1DUDE** [comment]
I saw you loaded the script from a different domain then the google sites domain, that probably has something to do with it based on the stackoverflow link I posted

**Comment by LAX1DUDE** [comment]
store the script and assets in an invisible div object and load them into the page that way

**Comment by Abnumality** [comment]
> store the script and assets in an invisible div object as text and load them into the page that way

could you give me a code example

**Comment by LAX1DUDE** [comment]
[Offline_Download_Version.html](https://raw.githubusercontent.com/LAX1DUDE/eaglercraft/main/stable-download/Offline_Download_Version.html)

Right click this link and press 'save as'.

**Comment by Abnumality** [comment]
I’ll test this tomorrow. Haven’t had much time as of recent

**Comment by Abnumality** [comment]
I found the issue. You have to use .focus() on the iframe.
