### ISSUE TITLE
External users not able to connect

### ISSUE THREAD

**Issue by primitt** [LAX1DUDE/eaglercraft#38]
So, some of my friends tried to connect to my server (port forwarded and everything) and failed.  Do I have to change anything in the config?
![image](https://user-images.githubusercontent.com/81822069/151684130-6c71d55e-8fc8-4180-a3e1-5385fd6fd539.png)

**Comment by LAX1DUDE** [comment]
What site, the g.eags.us one only supports the wss:// protocol, you need to host the page on your own regular non-https site for the browser to allow you to connect to a ws:// address like what eaglercraft bungeecord provides by default.

**Comment by primitt** [comment]
> What site, the g.eags.us one only supports the wss:// protocol, you need to host the page on your own regular non-https site for the browser to allow you to connect to a ws:// address like what eaglercraft bungeecord provides by default.

I just use the IP... (IP:25565)

**Comment by primitt** [comment]
OHH i understand! Ok then!

**Comment by primitt** [comment]
> What site, the g.eags.us one only supports the wss:// protocol, you need to host the page on your own regular non-https site for the browser to allow you to connect to a ws:// address like what eaglercraft bungeecord provides by default.

So, if I add an SSL cert to it, will it work?

**Comment by LAX1DUDE** [comment]
> So, if I add an SSL cert to it, will it work?

Yes it will work, but SSL is not directly implemented in eaglercraft bungeecord. The server is designed to run behind a reverse HTTP proxy like nginx or cloudflare to facilitate URL-based server connections, so I did not implement SSL directly in bungeecord because it is easier and safer and faster to configure it in the already existing reverse proxy that most likely already has SSL configured for it's regular traffic.
