### ISSUE TITLE
The Website Is Down!

### ISSUE THREAD

**Issue by schoolgaminghd** [LAX1DUDE/eaglercraft#4]
Hello LAX1DUDE! This project really impressed me. But there is just one issue, the website is down. I have compiled it to my own ip, but ip addresses are blocked at school. if you could, can you please bring back up the website.

**Comment by schoolgaminghd** [comment]
also if you cannot get the website back up can you please put in more user friendly instructions for getting a local server up! thank you

**Comment by LAX1DUDE** [comment]
Yeah I’ll replace the website today, I keep blowing it off but it’s a reasonably simple task. Try making a google sites page or weebly or something and embed the game there. I used to have a ‘javascript:’ uri bookmark that used the DOM, when clicked, to empty the <body> of the website and give it the “game_frame” id (see javascript/index.html) and give it a <script> tag to the classes.js and then launch the game that way, but I’ve discovered in the past year since making this that chrome disabled these types of bookmarks. You could still put the javascript: uri just in an regular <a> element and find somewhere online to embed it to get chrome to let you click it somehow

**Comment by schoolgaminghd** [comment]
ok thanks!

**Comment by schoolgaminghd** [comment]
Also, When i try to run it locally i get this error.
![Screenshot 2021-12-17 11 15 35 AM](https://user-images.githubusercontent.com/95301695/146574959-e9d0f476-c4eb-474f-8114-b74f9a5352f3.png)

**Comment by nik0dev** [comment]
If you're just opening the index.html, that work work due to CORS

**Comment by schoolgaminghd** [comment]
ok thanks!

**Comment by schoolgaminghd** [comment]
I hosting a site: http://eaglercraft.atwebpages.com/

**Comment by schoolgaminghd** [comment]
nvm you cannot connect to servers lol

**Comment by nik0dev** [comment]
You need to build the eagler bungeecord. You'll have to figure out how since I got my copy from a friend.

**Comment by schoolgaminghd** [comment]
ugh this is so hard.

**Comment by LAX1DUDE** [comment]
I’ll just start uploading the compiled binaries of the latest commits to the root of the repository myself to save everyone the trouble of compiling this. there’s nothing platform specific about the binaries like with C++ or something like that so there’s no incentive for people compile manually unless they’re fixing a bug

**Comment by LAX1DUDE** [comment]
and I’ll host a working copy of the websocket bungeecord server on my domain for quick multiplayer tests to prove the source actually works if you compile and set up bungee

**Comment by schoolgaminghd** [comment]
Ok, thanks a lot!

**Comment by LAX1DUDE** [comment]
okay you can download the latest binaries and example configuration here: [https://github.com/LAX1DUDE/eaglercraft/tree/main/stable-download](https://github.com/LAX1DUDE/eaglercraft/tree/main/stable-download)

I also did a lot of convenient maintenance, I fixed the problem with the cursor not grabbing in the pause menu that's probably pissing you all off right now, and I changed the title music to the regular minecraft title music instead of the annoying GTA music, and I changed the logos, and I fixed the corrupt characters on the title screen, and I updated my contact info in "eaglercraft readme.txt" too because I changed my insta username.
