### ISSUE TITLE
Error message of "Login timed out"

### ISSUE THREAD

**Issue by jach1337** [LAX1DUDE/eaglercraft#50]
Since yesterday, I have been playing on servers with little to no difficulty. This time, however, I have noticed that I am unable to join any servers; if I do try, I end up being automatically kicked with the message of "Login timed out". The only way I can fix this is by going on an alt account, but this resets all the progress I have made on my old account.

![image](https://user-images.githubusercontent.com/54753674/151913766-0615741c-0e1a-47ce-830e-ad9fe3db537a.png)

**Comment by LAX1DUDE** [comment]
You're not paying attention to the chat, there's a password set on this
profile name and the game is requesting you to use /login to enter the
password in the chat when you join but you're not doing it so it kicks you
after 30 seconds without entering the password. If you didn't set the
password then I'm sorry but I can't help you, I can't just reset random
passwords that's not fair, just make a new profile if you don't know the
password

**Comment by jach1337** [comment]
> You're not paying attention to the chat, there's a password set on this profile name and the game is requesting you to use /login to enter the password in the chat when you join but you're not doing it so it kicks you after 30 seconds without entering the password. If you didn't set the password then I'm sorry but I can't help you, I can't just reset random passwords that's not fair, just make a new profile if you don't know the password

Yeah, I know that I have to type /login every time I join that server. The problem is that I get kicked immediately, as soon as I join, so I can't even type in a single word before getting kicked. I know what my password is, the problem is that I'm not able to log in.

**Comment by LAX1DUDE** [comment]
> Yeah, I know that I have to type /login every time I join that server. The problem is that I get kicked immediately, as soon as I join, so I can't even type in a single word before getting kicked. I've already set a password and I know what my password is, the problem is that I'm not able to log in.

The server is severely overloaded, I thought I could move it to faster hardware and split it up into eight servers to reduce the load but I don't have enough upload bandwidth in my internet connection to allow more than 100 players at a time even though I have the resources allocated for 400 players. You are probably trying to join the server while it is almost full and it might be kicking you immediately to allow more players to join, I would imagine it is a security feature to prevent denial of service attacks on registration-only offline mode servers to guard them from people who can program the client to connect with 100 different profiles all at once and then just keep idling on the server and rejoining each time the authentication times out preventing anyone else from joining the server and logging in.

I currently do not have a solution to this problem because using AWS or Google Cloud or something like that to host the servers with full balanced multi-gigabit networking instead of my house's router's upload speed of only around 10mbps (I have 200+ mbps of download speed only my upload speed is limited to 10mbps) the cloud based virtual machine(s) to set the servers up will cost between $200 or $300 a month just for a simple plan with the same amount of RAM and CPU cores already in my current set of local servers in my garage. All I can really do is bug my dad to get fiber (which I don't think is available in my area) or upgrade the current plan but I think we're already paying somewhere in the neighborhood of $50 a month for that 10mbps upload over cable so I just don't know if it's worth investing hundreds of dollars by using the cloud or for paying more for internet just to allow for a little increase in capacity on a cracked minecraft server.

Sorry, I wish there was another way but it's just too expensive for a problem as small as an overloaded demo minecraft server full of kids I don't really know
