### ISSUE TITLE
world 

### ISSUE THREAD

**Issue by gy8ygyiuiuh** [LAX1DUDE/eaglercraft#55]
the worlds are only 1 chunk big and I spawned in the ground and can't find my base where me and my brother play plz if you can do something

**Comment by Cha0t1cDX** [comment]
Render distance?

**Comment by LAX1DUDE** [comment]
The servers are overloaded, I don’t feel like making the financial investment of paying for faster internet because it’s really expensive in my area and in the end I’m just facilitating piracy to a bunch of middle schoolers I don’t even know. This feed is for reporting bugs in the source code not for complaining about the demo servers please take this somewhere else
