### ISSUE TITLE
somethings up with title screen.

### ISSUE THREAD

**Issue by schoolgaminghd** [LAX1DUDE/eaglercraft#6]
![Screenshot 2021-12-18 7 31 06 PM](https://user-images.githubusercontent.com/95301695/146659269-24f4c710-8a6d-4953-a546-74506c5ee0ea.png)

**Comment by nik0dev** [comment]
That looks like how it normally looks??

**Comment by LAX1DUDE** [comment]
yeah I fixed all the unicode garbage everywhere and removed 'webassembly edition' text because this is just plain minified javascript I never got webassembly working. I fixed the servers on the multiplayer page on the demo ([https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/)) they work now you can try joining one if you still haven't seen any gameplay

**Comment by schoolgaminghd** [comment]
minceraft

**Comment by LAX1DUDE** [comment]
> minceraft

it's intentional, just for lols. few people in the history of minecraft have seen the minceraft easter egg personally

**Comment by schoolgaminghd** [comment]
ye i know just pointing it out
