### ISSUE TITLE
I cannot join servers if I type in the IP

### ISSUE THREAD

**Issue by JaylenAnderson** [LAX1DUDE/eaglercraft#62]
I can't seem to join servers but when I go into offline mode, it works perfectly fine. Someone please help me?

**Comment by JVGA8837** [comment]
What server are you trying to join. And eaglercraft only supports wss connections

**Comment by LAX1DUDE** [comment]
> What server are you trying to join. And eaglercraft only supports wss connections

The specific copy of the game on g.eags.us link doesn’t allow ws:// connections to servers it only supports wss:// because of browser security limitations for all sites hosted on an HTTPS url, the offline version is able to connect to everything because the browser doesn’t consider a local file to be a secure page but because my demo site is on HTTPS it is restricted to only secure servers using wss:// which is not a bug
