### ISSUE TITLE
help

### ISSUE THREAD

**Issue by MeekHercules389** [LAX1DUDE/eaglercraft#93]
i cant run any community made servers on my Chromebook i dont know if it is just because i have school WiFi or what can you please help?

**Comment by JVGA8837** [comment]
https://g.eags.us/eaglercraft/servers/

**Comment by MeekHercules389** [comment]
> https://g.eags.us/eaglercraft/servers/

i know how to do that i just cant figure out if its my computer or if its me not under staining how to get the servers put in to eaglercraft

**Comment by LAX1DUDE** [comment]
> > https://g.eags.us/eaglercraft/servers/
> 
> i know how to do that i just cant figure out if its my computer or if its me not under staining how to get the servers put in to eaglercraft

don't join servers using the page at [https://g.eags.us/eaglercraft/](https://g.eags.us/eaglercraft/), this page only supports WSS:// servers, and almost all the servers on the forum are WS://. You need to contact whoever runs each of the servers on the forum that you want to join and use their link to load the game instead of my discontinued demo link.

**Comment by MeekHercules389** [comment]
thanks lax dude!
